timeout: 0
serial: yes
verbose: yes
default_entry: 1

/SavanXP
    comment: Kernel minimo freestanding sobre Limine x86_64 UEFI
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initramfs.cpio
    resolution: 1280x800x32
    cmdline: boot=serial
