#!/usr/bin/env python3
"""Emite la tabla de capacidades de SxMedia para este build de FFmpeg.

El punto de esto es que la lista la produce la misma configuracion que compilo la
biblioteca, no alguien que la escribio. Una lista de decodificadores escrita a mano
se desvía de lo que `--enable-decoder` dejo realmente dentro -- un
`--disable-decoder=h264`, o un configure al que se le cayo un componente, y la
lista sigue anunciando un archivo que el reproductor luego no abre. Ese fallo sale
como un bug del reproductor en vez de como un build que no es lo que dice ser.

De donde sale cada nombre:

- `config_components.h` dice que decodificadores se compilaron. Es el estado
  *resuelto* del configure, ya con los `--enable` y `--disable` aplicados, que es lo
  unico que importa.
- `libavcodec/codec_desc.c` dice como se llama cada uno y si es audio o video. Es
  la unica tabla de FFmpeg que tiene las dos cosas juntas, y el nombre de ahi es
  exactamente el que devuelve `avcodec_find_decoder` y por tanto el que llega a
  `claim_stream` y el que aparece en el aviso de un codec que no se puede reproducir.

No se intenta compilar un programa que pregunte a la biblioteca: el libav del port
es un archivo estatico cross-compilado y un programa del host no lo puede enlazar.
`codec_desc.c` y `config_components.h` son texto y se leen.

Se ejecuta desde `link.sh` y escribe en el directorio de build, junto a los otros
artefactos, no en el overlay: la tabla es una funcion de como se configuro FFmpeg,
y una copia commiteada seria una promesa sobre un build que nadie hizo.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

# El nombre del macro de configure y el nombre del codec difieren solo en caja y
# en el sufijo, y esta asercion es la que lo vigila. Si un dia hay una excepcion,
# este script falla con ella en vez de emitir un nombre que el reproductor no
# reconocera nunca.
DECODER_MACRO = re.compile(r"^#define CONFIG_(?P<name>[A-Z0-9_]+)_DECODER 1$")
DESCRIPTOR = re.compile(
    r"\.id\s*=\s*AV_CODEC_ID_(?P<id>[A-Z0-9_]+),\s*"
    r"\.type\s*=\s*AVMEDIA_TYPE_(?P<type>VIDEO|AUDIO),\s*"
    r"\.name\s*=\s*\"(?P<name>[a-z0-9_]+)\""
)

# AVMEDIA_TYPE_* to the vtable's SX_MEDIA_KIND_*, which are 1 and 2 respectively.
KIND_AUDIO = 1
KIND_VIDEO = 2


def configured_decoders(config_components: pathlib.Path) -> set[str]:
    """The decoder macros that resolved to enabled, in lower case."""
    enabled = set()
    for line in config_components.read_text(encoding="utf-8", errors="replace").splitlines():
        found = DECODER_MACRO.match(line.strip())
        if found is not None:
            enabled.add(found.group("name").lower())
    return enabled


def codec_kinds(source_codec_desc: pathlib.Path) -> dict[str, int]:
    """Codec id to kind, from the one table FFmpeg has that carries a type.

    `codec_desc.c` is keyed by id, not by name, and it does not list the float
    variants: `mp3float` and `mp2float` are decoders in their own right with
    `.p.name` of their own, and they share `AV_CODEC_ID_MP3` and `AV_CODEC_ID_MP2`
    with the integer decoders. So the *name* comes from the configure macro, which
    is the convention and which is what `av_codec_iterate` reports, and the
    *kind* is looked up by id here.
    """
    kinds: dict[str, int] = {}
    text = source_codec_desc.read_text(encoding="utf-8", errors="replace")
    for found in DESCRIPTOR.finditer(text):
        kinds[found.group("id").lower()] = KIND_VIDEO if found.group("type") == "VIDEO" else KIND_AUDIO
    return kinds


def build_rows(enabled: set[str], kinds: dict[str, int]) -> tuple[list[tuple[str, int]], int]:
    """Every enabled decoder, named and sorted.

    A macro with no descriptor in `codec_desc.c` is assumed to be audio, and the
    count is returned so the caller can print it. Every such codec in FFmpeg is a
    float variant of an integer audio decoder -- there are no video variants --
    and `AVMEDIA_TYPE_AUDIO` is the answer for all of them. Assuming is only
    acceptable because it is *counted*: a future video variant would show up as a
    mislabelled row in a report rather than as a silent wrong answer.
    """
    rows = []
    assumed = 0
    for macro in sorted(enabled):
        kind = kinds.get(macro)
        if kind is None:
            kind = KIND_AUDIO
            assumed += 1
        rows.append((macro, kind))
    return rows, assumed


def render(rows: list[tuple[str, int]], decoder_macro_count: int) -> str:
    """The generated header.

    `SX_MEDIA_CODEC_CAPACITY` is 32 and the longest libav decoder name is under it;
    the emitted names are checked against it so a future rename cannot quietly
    produce a truncated entry.
    """
    lines = [
        "/* Generated by ports/ffmpeg/tools/gen_sxmedia_caps.py. Do not edit.",
        " *",
        f" * {len(rows)} decoders in this libav build, from config_components.h and",
        " * libavcodec/codec_desc.c. The names are libav's own, which is what reaches",
        " * `claim_stream` and what a notice shows. Regenerate with `link.sh`.",
        " */",
        "",
        "struct sx_media_codec_entry {",
        "    const char* name;",
        "    int kind;",
        "};",
        "",
        "static const struct sx_media_codec_entry kFFmpegCodecs[] = {",
    ]
    for name, kind in rows:
        if len(name) >= 32:
            raise SystemExit(f"sxmedia-caps: decoder name {name!r} does not fit the 32 bytes available")
        lines.append(f'    {{"{name}", {kind}}},')
    lines.append("};")
    lines.append("")
    if decoder_macro_count != len(rows):
        lines.append(
            f"/* {decoder_macro_count} decoder macros were enabled and {len(rows)} rows were"
            " written; those numbers should match. */"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config-components", type=pathlib.Path, required=True)
    parser.add_argument("--codec-desc", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    enabled = configured_decoders(args.config_components)
    if not enabled:
        raise SystemExit(f"sxmedia-caps: no decoders enabled in {args.config_components}")
    rows, assumed = build_rows(enabled, codec_kinds(args.codec_desc))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(rows, len(enabled)), encoding="utf-8")
    print(
        f"sxmedia-caps: {len(rows)} decoders "
        f"({sum(1 for _, kind in rows if kind == KIND_AUDIO)} audio, "
        f"{sum(1 for _, kind in rows if kind == KIND_VIDEO)} video) -> {args.output}"
    )
    if assumed:
        print(
            f"sxmedia-caps: {assumed} decoder(s) have no codec_desc.c entry and were "
            f"recorded as audio; they are the float variants",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
