#pragma once

#define SAVANXP_VERSION_MAJOR 0
#define SAVANXP_VERSION_MINOR 1
#define SAVANXP_VERSION_PATCH 4

#define SAVANXP_STRINGIFY_INNER(value) #value
#define SAVANXP_STRINGIFY(value) SAVANXP_STRINGIFY_INNER(value)

#define SAVANXP_SYSTEM_NAME "SavanXP"
#define SAVANXP_VERSION_STRING \
    "v" SAVANXP_STRINGIFY(SAVANXP_VERSION_MAJOR) "." SAVANXP_STRINGIFY(SAVANXP_VERSION_MINOR) "." SAVANXP_STRINGIFY(SAVANXP_VERSION_PATCH)
#define SAVANXP_DISPLAY_NAME SAVANXP_SYSTEM_NAME " " SAVANXP_VERSION_STRING
