param(
    [string]$Source = (Join-Path $PSScriptRoot "font8x8.txt"),
    [string]$Output = (Join-Path $PSScriptRoot "..\..\subsystems\posix\sdk\v1\runtime\gfx_font8x8.inc")
)

# Convert an 8x8 ASCII-art font source into a C glyph table.
# Source format: each glyph is one '@' marker line (e.g. "@ 0x41 A") followed by
# exactly 8 rows of 8 cells, where '#' is an on pixel and any other char is off.
# Bit 7 (0x80) is the leftmost column, row order is top to bottom.

$lines = Get-Content -LiteralPath $Source
$rows = New-Object System.Collections.Generic.List[string]
$labels = New-Object System.Collections.Generic.List[string]

foreach ($line in $lines) {
    if ($line -match '^\s*@\s*(.*)$') {
        $labels.Add($Matches[1].Trim())
        continue
    }
    if ($line -match '^\s*//') { continue }
    if ($line.Trim().Length -eq 0) { continue }
    $rows.Add($line)
}

if ($rows.Count % 8 -ne 0) {
    throw "Font source has $($rows.Count) pixel rows, not a multiple of 8."
}

$glyphCount = $rows.Count / 8
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by tools/font/genfont.ps1 from font8x8.txt - do not edit by hand. */")
[void]$sb.AppendLine("static const unsigned char kGfxGlyphs[$glyphCount][8] = {")

for ($g = 0; $g -lt $glyphCount; $g++) {
    $bytes = @()
    for ($r = 0; $r -lt 8; $r++) {
        $row = $rows[$g * 8 + $r]
        $value = 0
        for ($c = 0; $c -lt 8; $c++) {
            if ($c -lt $row.Length -and $row[$c] -eq '#') {
                $value = $value -bor (1 -shl (7 - $c))
            }
        }
        $bytes += ('0x{0:x2}' -f $value)
    }
    $label = if ($g -lt $labels.Count) { " /* $($labels[$g]) */" } else { "" }
    [void]$sb.AppendLine("    {" + ($bytes -join ", ") + "},$label")
}

[void]$sb.AppendLine("};")
Set-Content -LiteralPath $Output -Value $sb.ToString() -Encoding ascii
Write-Output "Wrote $glyphCount glyphs to $Output"
