#!/usr/bin/env python3
"""Bake TrueType fonts into C glyph tables (.inc) for SavanXP.

The OS does not parse TrueType at runtime: glyphs are rasterised offline here
and the generated .inc files are committed for reproducible builds.

Two modes:

  unifont  -> 1-bit fixed 8x16 console font baked from GNU UniFont's canonical
              .hex bitmaps (ASCII + Latin-1 + box drawing / block elements).
              The .hex source is used because UniFont is a bitmap font: its TTF
              is outline-only and rasterises off-grid with artefacts. Consumed
              by the kernel framebuffer console and the gfx monospace text path.

  noto     -> 8-bit coverage (antialiased) proportional UI font (Noto Sans),
              rasterised from the TTF outline. ASCII + Latin-1. Consumed by the
              gfx proportional text path. Requires freetype-py.

Regenerate (run from repo root):
  python tools/font/genfont.py unifont \
      --hex assets/desktop/fonts/unifont.hex \
      --out include/kernel/console_font_unifont.inc \
      --out subsystems/posix/sdk/v1/runtime/console_font_unifont.inc
  python tools/font/genfont.py noto \
      --ttf assets/desktop/fonts/NotoSans-Regular.ttf \
      --out subsystems/posix/sdk/v1/runtime/gfx_font_noto.inc
  python tools/font/genfont.py noto \
      --ttf assets/desktop/fonts/NotoSans-Regular.ttf --size 12 \
      --prefix SX_NOTO_TITLE --bold 1 \
      --out subsystems/posix/sdk/v1/runtime/gfx_font_noto_title.inc
"""

import argparse
import os
import sys

# Cell geometry for the UniFont console glyphs.
UNI_CELL_W = 8
UNI_CELL_H = 16

# Codepoint ranges baked into the console font (inclusive). Slot 0 is reserved
# for .notdef, so real glyphs are assigned slots starting at 1.
UNI_RANGES = [
    (0x20, 0xFF),    # ASCII + Latin-1
    (0x2500, 0x257F),  # box drawing
    (0x2580, 0x259F),  # block elements
]

# Same idea for the proportional UI font. Latin-1 covers the accented letters the
# Spanish UI needs; the punctuation block is what a UI actually reaches for
# (en/em dash, curly quotes, ellipsis, bullet). Kept deliberately small: this
# table is linked into every binary.
NOTO_RANGES = [
    (0x20, 0xFF),      # ASCII + Latin-1
    (0x2010, 0x2027),  # dashes, curly quotes, bullet, ellipsis
    (0x20AC, 0x20AC),  # euro sign
]


def _parse_hex(path):
    """Parse a GNU UniFont .hex file into {codepoint: [16 row bytes]}.

    Each line is 'CCCC:hhhh...'. The bitmap is 16 rows; an 8-wide glyph encodes
    one byte per row (32 hex chars), a 16-wide glyph two bytes per row (64). We
    keep the leftmost 8 columns so every glyph lands in the fixed 8x16 cell;
    the baked ranges are all single-width, so no real data is clipped.
    """
    table = {}
    with open(path, "r", encoding="ascii") as fh:
        for line in fh:
            line = line.strip()
            if not line or ":" not in line:
                continue
            code, bits = line.split(":", 1)
            cp = int(code, 16)
            nbytes = len(bits) // 2
            stride = nbytes // UNI_CELL_H  # 1 (8-wide) or 2 (16-wide)
            if stride == 0:
                continue
            rows = []
            for r in range(UNI_CELL_H):
                base = (r * stride) * 2
                rows.append(int(bits[base:base + 2], 16))  # leftmost byte
            table[cp] = rows
    return table


def gen_unifont(hexpath, outs):
    table = _parse_hex(hexpath)
    blank = [0] * UNI_CELL_H

    glyphs = []
    # Slot 0: .notdef -> replacement char if present, else blank.
    glyphs.append(table.get(0xFFFD, blank))

    ranges = []  # (first, last, base_slot)
    for first, last in UNI_RANGES:
        base = len(glyphs)
        for cp in range(first, last + 1):
            glyphs.append(table.get(cp, blank))
        ranges.append((first, last, base))

    sb = []
    sb.append("/* Generated by tools/font/genfont.py (mode unifont) from %s." %
              os.path.basename(hexpath))
    sb.append(" * Do not edit by hand. See tools/font/genfont.py header to regenerate. */")
    sb.append("#define SX_CONSOLE_GLYPH_W %d" % UNI_CELL_W)
    sb.append("#define SX_CONSOLE_GLYPH_H %d" % UNI_CELL_H)
    sb.append("")
    sb.append("static const unsigned char kConsoleGlyphs[%d][%d] = {" %
              (len(glyphs), UNI_CELL_H))
    for slot, rows in enumerate(glyphs):
        body = ", ".join("0x%02x" % b for b in rows)
        sb.append("    {%s}, /* slot %d */" % (body, slot))
    sb.append("};")
    sb.append("")
    sb.append("struct sx_console_glyph_range { unsigned int first; unsigned int last; unsigned int base; };")
    sb.append("static const struct sx_console_glyph_range kConsoleGlyphRanges[] = {")
    for first, last, base in ranges:
        sb.append("    {0x%04x, 0x%04x, %d}," % (first, last, base))
    sb.append("};")
    sb.append("static const int kConsoleGlyphRangeCount = %d;" % len(ranges))
    sb.append("")
    sb.append("/* Look up a codepoint, falling back to slot 0 (.notdef). */")
    sb.append("static inline const unsigned char* sx_console_glyph(unsigned int cp) {")
    sb.append("    int i;")
    sb.append("    for (i = 0; i < kConsoleGlyphRangeCount; ++i) {")
    sb.append("        if (cp >= kConsoleGlyphRanges[i].first && cp <= kConsoleGlyphRanges[i].last) {")
    sb.append("            return kConsoleGlyphs[kConsoleGlyphRanges[i].base + (cp - kConsoleGlyphRanges[i].first)];")
    sb.append("        }")
    sb.append("    }")
    sb.append("    return kConsoleGlyphs[0];")
    sb.append("}")
    sb.append("")
    text = "\n".join(sb)
    for out in outs:
        _write(out, text)
        print("Wrote %d console glyphs to %s" % (len(glyphs), out))


def _noto_symbols(prefix):
    """Return C identifiers for one generated Noto face.

    Keeping the prefix in one place lets the same source font produce the normal
    UI face and a separately-sized caption face without making the generated
    tables collide when both are included in the POSIX runtime.
    """
    normalized = prefix.strip("_")
    all_parts = normalized.lower().split("_")
    parts = all_parts[1:] if all_parts[:2] == ["sx", "noto"] else all_parts
    if (len(all_parts) < 2 or all_parts[:2] != ["sx", "noto"] or
            not all(part.isidentifier() for part in all_parts)):
        raise ValueError("Noto symbol prefix must start with SX_NOTO and contain C identifiers: %s" % prefix)
    words = [part.capitalize() for part in parts]
    return {
        "macro": normalized.upper(),
        "type": "_".join(["sx"] + parts) + "_glyph",
        "range_type": "_".join(["sx"] + parts) + "_glyph_range",
        "array": "k" + "".join(words) + "Glyphs",
        "ranges": "k" + "".join(words) + "GlyphRanges",
        "coverage": "k" + "".join(words) + "Coverage",
        "range_count": "k" + "".join(words) + "GlyphRangeCount",
        "coverage_size": "k" + "".join(words) + "CoverageSize",
        "lookup": "_".join(["sx"] + parts) + "_glyph",
    }


def gen_noto(ttf, size, outs, prefix="SX_NOTO", bold=0):
    if size <= 0:
        raise ValueError("Noto font size must be positive")
    if bold < 0:
        raise ValueError("Noto faux-bold width cannot be negative")

    symbols = _noto_symbols(prefix)
    try:
        import freetype
    except ImportError:
        sys.exit("noto mode needs freetype-py: pip install freetype-py")
    face = freetype.Face(ttf)
    face.set_pixel_sizes(0, size)
    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)
    line_height = face.size.height >> 6

    coverage = []
    glyphs = []  # (width, rows, left, top, advance, offset)

    def bake(cp):
        face.load_char(cp, freetype.FT_LOAD_RENDER)
        g = face.glyph
        bmp = g.bitmap
        offset = len(coverage)
        width = bmp.width
        for gy in range(bmp.rows):
            base = gy * bmp.pitch
            row = [bmp.buffer[base + gx] for gx in range(bmp.width)]
            if bold and width:
                # A small right-hand dilation is a deterministic faux bold that
                # keeps the source asset small and works at the tiny sizes used
                # by caption text. The advance stays the face's advance, just as
                # a real bold face usually keeps the text layout close.
                row = [
                    max(row[source_column]
                        for source_column in range(max(0, output_column - bold), output_column + 1)
                        if source_column < width)
                    for output_column in range(width + bold)
                ]
            coverage.extend(row)
        if bold and width:
            width += bold
        glyphs.append((width, bmp.rows, g.bitmap_left, g.bitmap_top,
                       g.advance.x >> 6, offset))

    # Slot 0 is the fallback for anything unmapped. Space, not .notdef: an
    # unknown codepoint should advance the pen, not draw a tofu box in the middle
    # of a label. This matches what the byte-indexed table did before, where an
    # out-of-range char fell back to kNotoGlyphs[0] == space.
    bake(0x20)
    slot_of = []  # (first, last, base_slot)
    for first, last in NOTO_RANGES:
        base = len(glyphs)
        for cp in range(first, last + 1):
            bake(cp)
        slot_of.append((first, last, base))

    sb = []
    style = " with %dpx faux-bold" % bold if bold else ""
    sb.append("/* Generated by tools/font/genfont.py (mode noto) from %s @ %dpx%s." %
              (os.path.basename(ttf), size, style))
    sb.append(" * Do not edit by hand. See tools/font/genfont.py header to regenerate. */")
    sb.append("#define %s_ASCENT %d" % (symbols["macro"], ascent))
    sb.append("#define %s_DESCENT %d" % (symbols["macro"], descent))
    sb.append("#define %s_LINE_HEIGHT %d" % (symbols["macro"], line_height))
    sb.append("")
    sb.append("struct %s {" % symbols["type"])
    sb.append("    short width;")
    sb.append("    short rows;")
    sb.append("    short left;")
    sb.append("    short top;")
    sb.append("    short advance;")
    sb.append("    unsigned int offset;")
    sb.append("};")
    sb.append("")
    labels = ["fallback"]
    for first, last in NOTO_RANGES:
        labels.extend("0x%04x" % cp for cp in range(first, last + 1))
    sb.append("static const struct %s %s[%d] = {" %
              (symbols["type"], symbols["array"], len(glyphs)))
    for label, (w, r, l, t, a, o) in zip(labels, glyphs):
        sb.append("    {%d, %d, %d, %d, %d, %d}, /* %s */" % (w, r, l, t, a, o, label))
    sb.append("};")
    sb.append("")
    sb.append("struct %s { unsigned int first; unsigned int last; unsigned int base; };" %
              symbols["range_type"])
    sb.append("static const struct %s %s[] = {" %
              (symbols["range_type"], symbols["ranges"]))
    for first, last, base in slot_of:
        sb.append("    {0x%04x, 0x%04x, %d}," % (first, last, base))
    sb.append("};")
    sb.append("static const int %s = %d;" % (symbols["range_count"], len(slot_of)))
    sb.append("")
    sb.append("/* Look up a codepoint, falling back to slot 0 (space). */")
    sb.append("static inline const struct %s* %s(unsigned int cp) {" %
              (symbols["type"], symbols["lookup"]))
    sb.append("    int i;")
    sb.append("    for (i = 0; i < %s; ++i) {" % symbols["range_count"])
    sb.append("        if (cp >= %s[i].first && cp <= %s[i].last) {" %
              (symbols["ranges"], symbols["ranges"]))
    sb.append("            return &%s[%s[i].base + (cp - %s[i].first)];" %
              (symbols["array"], symbols["ranges"], symbols["ranges"]))
    sb.append("        }")
    sb.append("    }")
    sb.append("    return &%s[0];" % symbols["array"])
    sb.append("}")
    sb.append("")
    sb.append("static const unsigned char %s[] = {" % symbols["coverage"])
    line = "    "
    for i, v in enumerate(coverage):
        line += "0x%02x," % v
        if len(line) >= 96:
            sb.append(line)
            line = "    "
    if line.strip():
        sb.append(line)
    sb.append("};")
    sb.append("static const unsigned int %s = %d;" % (symbols["coverage_size"], len(coverage)))
    sb.append("")
    text = "\n".join(sb)
    for out in outs:
        _write(out, text)
        print("Wrote %d Noto glyphs (%d coverage bytes) to %s" %
              (len(glyphs), len(coverage), out))


def _write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write(text)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="mode", required=True)

    u = sub.add_parser("unifont", help="bake 1-bit 8x16 console font from .hex")
    u.add_argument("--hex", dest="hexpath", required=True)
    u.add_argument("--out", action="append", required=True)

    n = sub.add_parser("noto", help="bake 8-bit proportional UI font")
    n.add_argument("--ttf", required=True)
    n.add_argument("--size", type=int, default=13)
    n.add_argument("--prefix", default="SX_NOTO",
                   help="C symbol prefix (default: SX_NOTO)")
    n.add_argument("--bold", type=int, default=0, metavar="PIXELS",
                   help="add this many pixels of faux-bold coverage")
    n.add_argument("--out", action="append", required=True)

    args = ap.parse_args()
    if args.mode == "unifont":
        gen_unifont(args.hexpath, args.out)
    elif args.mode == "noto":
        gen_noto(args.ttf, args.size, args.out, args.prefix, args.bold)


if __name__ == "__main__":
    main()
